version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3307:3306"
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: restaurante
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: "uMtSqR=pcdBW!12"
      MYSQL_USER: userlucas
      MYSQL_PASSWORD: "passlucas"
      MYSQL_ROOT_HOST: 'localhost'
  backend:
    depends_on:
      - db
    build: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    networks:
      - app-tier