version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  app:
    container_name: "api-restaurante"
    build: .
    command: bash -c 'npm start'
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-tier
    restart: always